# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Boristest < Formula
  desc ""
  homepage "https://github.com/borischen0203/homebrew-boristest"
  version "0.0.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/boristest/releases/download/v0.0.3/boristest_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "21c0f5498d43b13e533bb8e103127979255d93d8bf6329c3c77488d8dfcff72b"
    end
    if Hardware::CPU.arm?
      url "https://github.com/borischen0203/boristest/releases/download/v0.0.3/boristest_0.0.3_Darwin_arm64.tar.gz"
      sha256 "2eb3887679dbdca2c03ed2e21e2e2157ef6e9ab2b20c3e28987ab16837a0a1da"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/borischen0203/boristest/releases/download/v0.0.3/boristest_0.0.3_Linux_arm64.tar.gz"
      sha256 "900ca081c573e76115a74189727b015ddf407f25fc7a889dfcd02e299b7ef55b"
    end
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/boristest/releases/download/v0.0.3/boristest_0.0.3_Linux_x86_64.tar.gz"
      sha256 "c8f0cb0dd97c4237fc6ab579c7dc85cb09ca828e7f77bc57207ba386111e3c16"
    end
  end

  def install
    bin.install "boristest"
  end
end
