# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Boristest < Formula
  desc ""
  homepage "https://github.com/scraly/homebrew-boristest"
  version "0.0.2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/borischen0203/boristest/releases/download/v0.0.2/boristest_0.0.2_Darwin_arm64.tar.gz"
      sha256 "34d9b63551c4a1ae91a9c12de1fb3115a17842d1d9c8d975828d4d10b8ba33f9"
    end
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/boristest/releases/download/v0.0.2/boristest_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "16900727d93b78683261b17e9435e10d382fde3a0bcaa062a6618cf27e7ea043"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/borischen0203/boristest/releases/download/v0.0.2/boristest_0.0.2_Linux_x86_64.tar.gz"
      sha256 "a0894a57f9e3bb3822d9770e8dfaf9fc3597ac5cebfc2e5cf416861f9e926854"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/borischen0203/boristest/releases/download/v0.0.2/boristest_0.0.2_Linux_arm64.tar.gz"
      sha256 "008c56d46e1468cbe1645c3af882be09baa3327fa30c7f8e0ded7add976c5ac9"
    end
  end

  def install
    bin.install "boristest"
  end
end
